### ISSUE TITLE
Generator crash 'panic: 27217:22: expected '}', found 'IDENT' int'

### ISSUE THREAD

**Issue by klauspost** [ugorji/go#52]
When running codecgen against the ffjson test set I got this error:
```
c:\GoPath\src\github.com\pquerna\ffjson\tests>codecgen -o ff_codec.go ff.go
codecgen error: Error running go run codecgen-1424087427033171900.generated.go.
Error: exit status 1. stdout/err: panic: 27217:22: expected '}', found 'IDENT' i
nt (and 10 more errors)

goroutine 1 [running]:
main.main()
        c:/GoPath/src/github.com/pquerna/ffjson/tests/codecgen-14240874270331719
00.generated.go:422 +0x1103f
exit status 2
```

```sh
go get -u github.com/pquerna/ffjson
cd github.com/pquerna/ffjson/tests  (in gopath)
codecgen -o ff_codec.go ff.go
```

Also, you might want to update the information on [your blog](http://ugorji.net/blog/go-codecgen) - all of the points you mention about ffjson is no longer true. Decoding is now supported, struct renaming works, and generating values.go:TestStruct works.

**Comment by ugorji** [comment]
BTW, I couldn't get the ffjson generated code to run on TestStruc. It now generates fine,
but gives a runtime error when running. These errors occurred during encoding and decoding.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x580d23]

goroutine 9 [running]:
encoding/json.func·002()
	/home/ugorji/opt/go-release/src/encoding/json/encode.go:262 +0x8b
ugorji.net/codec.(*TestStruc).MarshalJSONBuf(0xc2080301e0, 0x7f119b22ced0, 0xc208084120, 0x0, 0x0)
	/home/ugorji/depot/repo/src/ugorji.net/codec/values_ffjson_generated_test.go:2448 +0x2aa3
ugorji.net/codec.(*TestStruc).MarshalJSON(0xc2080301e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ugorji/depot/repo/src/ugorji.net/codec/values_ffjson_generated_test.go:2152 +0xb6
```
